### ISSUE TITLE
Population increase comparison

### ISSUE THREAD

**Issue by anklinv** [anklinv/Scalable_Genetic_Algorithm#38]
- [x] Test whether population increase scales linearly (probably not)

**Comment by 1011han** [comment]
- done for berlin52.csv
- done for a280.csv

**Comment by 1011han** [comment]
- done for bier127.csv (5 repetitions)
- done for ch130.csv (5 repetitions)

the results seem to be a bit inconsistent

**Comment by 1011han** [comment]
[grid_search_images__Copy_.pdf](https://github.com/anklinv/Scalable_Genetic_Algorithm/files/3901025/grid_search_images__Copy_.pdf)

**Comment by 1011han** [comment]
[grid_search_images__Copy___Copy_.pdf](https://github.com/anklinv/Scalable_Genetic_Algorithm/files/3903042/grid_search_images__Copy___Copy_.pdf)
- caution: the colors are not the same for each settings on different plots
- the results are different from the fitness / epoch
- 50% - 80% elite size works better (interpretation: fewer mutations per epoch means faster epochs)
